apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sofus-jenkins
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: student-0
  syncPolicy:
    automated: {}
  sources:
    - repoURL: 'https://charts.bitnami.com/bitnami'
      targetRevision: 12.4.4
      helm:
        valueFiles:
          - $values/jenkins/values.yaml
      chart: jenkins
    - repoURL: 'https://github.com/sofusalbertsen/ideal-doodle'
      targetRevision: main
      ref: values
